name: "Build main"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx5g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: build --scan --full-stacktrace

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Upload Code Scanning code analysis report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'build/reports/detekt/main.sarif'
